### ISSUE TITLE
Define story for ordering product via inbox

### ISSUE THREAD

**Issue by domanhdoan** [domanhdoan/auto-sale#55]

**Comment by nghiatrongnguyen** [comment]
Các câu hỏi thường gặp của khách hàng mua giầy tại cửa hàng bluewind
1. GIÁ
2. Đôi này giá bao nhiêu?
3. Mua 2 đôi thì giá bao nhiêu?
4. Còn giá combo chứ?
5. Giày rẻ nhất giá bao nhiêu?
6. Có bớt không?
7. Có chiết khấu không?
8. Không lấy quà tặng có được giảm giá không?
9. SẴN HÀNG (availability)
10. Đôi này còn không?
11. Đôi này size xxx còn không?
12. Còn size xxx với yyy không?
13. Có đủ size không?
14. Có mầu yyy không?
15. Shop có chuck ll không?
16. Có đến size bao nhiêu?
17. SHIP HÀNG
18. Có ship đến zzz không?
19. Ship đến zzz thì hết bao nhiêu?
20. Mình ở zzz thì bao lâu nhận được hàng?
21. Free ship hả shop?
22. Có ship COD không?
23. OTHERS
24. Có ảnh thật của đôi này không
25. Đế cứng hay đế mềm?
26. Giày có tốt không?
27. Có bền không?
28. Giày bằng nhung hả shop?
29. Địa chỉ shop ở đâu?
30. Mình nhận được hàng rồi. Muốn đổi lên size kkk thì có được không?  
31. Mình muốn mua giày đôi. Shop tư vấn đôi nào nhẹ, ôm chân nhưng không quá to được không?
32. Shop ơi bên mình mở cửa đến mấy giờ?
33. Bảo hành, đổi trả như thế nào?
